### ISSUE TITLE
It does not work with Kubernetes v1.22+

### ISSUE THREAD

**Issue by adidenko** [Mirantis/k8s-netchecker-server#128]
Kubernetes v1.22 removes a lot of previously deprecated apiVersions, and k8s-netchecker-server uses a lot of outdated libraries and removed apiVersions which leads to crashes.

Log from the Pod:
```
I0125 10:22:25.362825       1 server.go:48] K8s netchecker. Compiled at: 20180102-12:47:46-UTC
I0125 10:22:25.362915       1 server.go:54] Start listening on 0.0.0.0:8081
E0125 10:22:25.372368       1 storer_k8s.go:68] the server could not find the requested resource
E0125 10:22:25.372390       1 server.go:58] Error while setting up the handler. Details: the server could not find the requested resource
panic: the server could not find the requested resource

goroutine 1 [running]:
main.main()
	/home/travis/gopath/src/github.com/Mirantis/k8s-netchecker-server/cmd/server.go:59 +0x6d3
```

**Comment by anders-elastisys** [comment]
Same issue here (on v1.23.7), I tried to install netchecker-server using Helm and had to change the apiVersions as they were deprecated and then I got the exact same logs.

**Comment by ekochen** [comment]
same issue with k8s 1.26.13
